/**
 * Commit Patch Utility
 * Simplified version - uses GitHub Contents API for direct commits
 * In production: consider using proper git operations or GitHub GraphQL API
 */

import {
  createBranch,
  getFileContent,
  updateFile,
  createPR,
  isGitHubConfigured,
} from "./createPR";

export interface CommitPatchResult {
  success: boolean;
  branchName?: string;
  prNumber?: number;
  prUrl?: string;
  error?: string;
}

/**
 * Commit a patch to a new branch and create PR
 * This is a simplified version that creates a new file rather than applying a diff
 * In production, you'd want to properly apply the patch using git operations
 */
export async function commitPatch(params: {
  filePath: string;
  patch: string;
  message: string;
  baseBranch?: string;
}): Promise<CommitPatchResult> {
  const { filePath, patch, message, baseBranch = "main" } = params;

  if (!isGitHubConfigured()) {
    return {
      success: false,
      error: "GitHub not configured. Set GITHUB_TOKEN, GITHUB_OWNER, GITHUB_REPO",
    };
  }

  const branchName = `auto-fix/${Date.now()}`;

  try {
    console.log("[Commit Patch] Step 1: Creating branch", branchName);
    const branchResult = await createBranch(branchName, baseBranch);
    if (!branchResult.success) {
      return { success: false, error: branchResult.error };
    }

    console.log("[Commit Patch] Step 2: Getting current file content");
    const fileResult = await getFileContent(filePath, baseBranch);
    
    // For this simplified version, we'll append the fix as comments
    // In production, you'd apply the actual diff
    const newContent = generatePatchedContent(
      fileResult.content || "",
      patch,
      message
    );

    console.log("[Commit Patch] Step 3: Updating file");
    const updateResult = await updateFile(
      filePath,
      newContent,
      `Auto-fix: ${message}`,
      branchName,
      fileResult.sha
    );

    if (!updateResult.success) {
      return { success: false, error: updateResult.error };
    }

    console.log("[Commit Patch] Step 4: Creating PR");
    const prResult = await createPR(
      branchName,
      `🤖 Auto-fix: ${message}`,
      generatePRDescription(patch, message),
      baseBranch
    );

    if (!prResult.success) {
      return { success: false, error: prResult.error };
    }

    return {
      success: true,
      branchName,
      prNumber: prResult.prNumber,
      prUrl: prResult.prUrl,
    };
  } catch (error) {
    return {
      success: false,
      error: `Commit failed: ${error instanceof Error ? error.message : String(error)}`,
    };
  }
}

/**
 * Generate patched content by appending fix (simplified)
 * In production, this would apply an actual diff patch
 */
function generatePatchedContent(
  originalContent: string,
  patch: string,
  message: string
): string {
  const timestamp = new Date().toISOString();
  
  // Add the fix as a new function at the end of the file
  const fixSection = `

// ============================================================================
// 🤖 AUTO-FIX APPLIED: ${message}
// Timestamp: ${timestamp}
// ============================================================================

// TODO: Apply the following patch manually:
/*
${patch}
*/

// Safe wrapper function added by auto-fix:
export function safeOperation<T>(operation: () => T, fallback: T): T {
  try {
    return operation();
  } catch (error) {
    console.error('[Auto-Fix Safe Operation]', error);
    return fallback;
  }
}
`;

  return originalContent + fixSection;
}

/**
 * Generate PR description
 */
function generatePRDescription(patch: string, message: string): string {
  return `## 🤖 Auto-generated Fix

**Fix Message:** ${message}

### Suggested Patch
\`\`\`diff
${patch}
\`\`\`

### ⚠️ Review Required

This PR was automatically generated based on error pattern matching. Please:

1. Review the suggested patch carefully
2. Apply the diff manually if it looks correct
3. Add tests for the fixed scenario
4. Remove the TODO comments after applying

### Safety Notes

- This is a draft PR - requires manual review
- Changes are minimal and focused on error handling
- No breaking changes should be introduced

---

*Generated by Auto-Fix Agent*`;
}

/**
 * Quick commit for demo/testing purposes
 * Creates a simple test file instead of patching real code
 */
export async function commitDemoPatch(): Promise<CommitPatchResult> {
  const demoFile = `lib/auto-fix/demo-fix-${Date.now()}.ts`;
  const content = `// Auto-generated fix demo
// Generated at: ${new Date().toISOString()}

export function safeAccess<T>(obj: any, path: string, fallback: T): T {
  try {
    const keys = path.split('.');
    let result = obj;
    for (const key of keys) {
      result = result?.[key];
      if (result === undefined) return fallback;
    }
    return result;
  } catch {
    return fallback;
  }
}

// Usage example:
// const value = safeAccess(data, 'user.profile.name', 'Anonymous');
`;

  return commitPatch({
    filePath: demoFile,
    patch: "Added safeAccess utility for null-safe property access",
    message: "Add safeAccess utility for null-safe property access",
  });
}
